#include<iostream>
using namespace std;
int main(){
    cout << "hello world" << endl;

    int i = 10;
    cout << i << endl;

    long l = 10000000;
    cout << l  << endl;

    long long ll = 1000000000000000;
    cout << ll << endl;

    double d = 10.001;
    cout << d << endl;

    float f = 10.65;
    cout << f << endl;

    string s = "Dishant";
    cout << s << endl;

    // string str ;
    // getline (cin ,str);
    // cout << str << endl;

    char c = 'a';
    cout << c << endl;

}